### ISSUE TITLE
Headless browser maintains cookies between snapshots

### ISSUE THREAD

**Issue by kevin-j-morse** [eWert-Online/OSnap#20]
I have a web application that I'm trying to visually diff using OSnap.

All pages are replaced with a login page for unauthenticated users. Depending on the order that tests are run, this tool doesn't require login for many of the tests which suggests that client state is being preserved between snapshots.

I think calling [Storage.clearCookies](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#method-clearCookies) on the browser before starting each test would address this issue. One could go further and clear the cache but I expect this would have a detrimental performance on the tests and is not reflective of a real world situation.

**Comment by eWert-Online** [comment]
This should now be fixed in the latest nightly version.
Would be be able to test this? 🙂
