### ISSUE TITLE
Name of snapshot directory wrong

### ISSUE THREAD

**Issue by ntzrbtr** [eWert-Online/OSnap#26]
If I set the "snapshotDirectory" to "./snapshots/live/", the created folder is "osnap./snapshots/live/", so it adds the dot to the generated folder name instead of taking it as marking a relative path.
Also, why is "osnap" always added to the front of the snapshot path, this is not in the docs?

**Comment by eWert-Online** [comment]
Hi @ntzrbtr 

thank you for reporting the issue. That should definetly not be the case. 

It would be good to know which operating system you are using and if you are running osnap inside docker (if so which docker image are you using). 

Would it be possible for you to create a small reproduction case and push it into a public repository?

**Comment by ntzrbtr** [comment]
I've set up a test repo under https://github.com/ntzrbtr/osnap-test. I included the snapshot folder generated so you can see the directory structure.

I've used OSnap on my M1 Mac directly, not with the Docker image.

**Comment by eWert-Online** [comment]
Awesome thank you! I will look into it (probably) this weekend 🙂

**Comment by eWert-Online** [comment]
@ntzrbtr I could identify the issue(s) and a fix for #26 and #27 is deployed in the latest `@nightly` tag.
To test it, you can install osnap in version `^1.5.0-nightly.d8a46a`.

Could you confirm, that this issues are resolved for you?

**Comment by ntzrbtr** [comment]
It works now, thanks for the update!
