### ISSUE TITLE
Move ignore regions detection to odiff?

### ISSUE THREAD

**Issue by dmtrKovalenko** [eWert-Online/osnap#3]
Just randomly looked into the sources and maybe we can move ignore regions to odiff in order to make this lib more efficient?

**Comment by eWert-Online** [comment]
I don't have ignore regions implemented yet.
But yes, as soon as I find time, I would like to implement them in odiff 🙂
Shouldn't be that hard to do. The only thing to think about a bit more carefully is the api to define one or more ignore regions.
