### ISSUE TITLE
Ablity to debug internal errors

### ISSUE THREAD

**Issue by selven** [eWert-Online/OSnap#39]
I have everything setup and working great locally. But once I try to run it in the ci I get:

```
osnap: internal error, uncaught exception:
       End_of_file
```

How would I go about debugging this issue and seeing the underlying error?

**Comment by eWert-Online** [comment]
Hmm... that error message can have multiple causes. 
The first that comes to mind is that you did not download the chromium version osnap needs. 

Did you run `osnap download`?

**Comment by selven** [comment]
Thank you, that was it. I guess I didn't have to run that locally because I already had chromium installed. It's working in the pipeline now.

**Comment by eWert-Online** [comment]
Thats great to hear 🙂 
I want to keep this issue open however, because I think the error message needs to be improved!

**Comment by selven** [comment]
Great and I double checked I didn't just miss it, that command needs to be added to the readme/ website somewhere (for non docker users).
